#!/bin/bash
#
# Copyright (c) 2015-2018 Vasilios E. Raptis <polyana.software@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#-----------------------------------------------------------------------
#
if [[ $# -eq 0 ]]
then
        echo " "
        echo " "
        echo "  Usage: "
        echo " "
        echo "          rdfplot [index of column to plot: 2, 3, ... ] [upper bound for y-axis]"
        echo " "
        echo " "

        exit 0;
fi

rm -f rdfplot.gp
touch rdfplot.gp

# This is the gnuplot script
read -r -d '' SCRIPT <<- scriptdelimiter
    set term x11 enhanced
    set style line 100 lt 1 lc rgb "gray50" lw 2
    set border ls 100
    unset key
    set yrange [0:$2]
    set size ratio 0.75
    set xlabel 'Distance [Angs]' offset 0,0
    set ylabel 'r.d.f.' rotate by 90 offset 0,0
    set xtics offset 0.3,0 textcolor rgb "gray10"
    set ytics textcolor rgb "gray10"
    set xzeroaxis ls 100 
    plot 'RDF' u 1:$1 w l lc rgb "red" lw 2
    pause -1
    set term png enhanced
    set output 'rdf.png'
    rep
scriptdelimiter

echo "$SCRIPT" >> rdfplot.gp

gnuplot rdfplot.gp

# rm rdfplot.gp
